### PR TITLE
package.json: fix version numbers

### PR DESCRIPTION
**Pull request by marado**
yarn.lock file still needs to be regenerated, tho

### CODE REVIEW

**Comment by marado** [comment]
BTW, I said that the yarn.lock file needed to be updated, but I actually doubt it will: after all we're accepting each dependency "up to the latest" version, and the yarn.lock file is showing the id for the latest. I'm not quite sure how that will work, tho, not being an yarn user yet, so I'd still like you to check if the file needs or not to be regenerated. In any case, I am curious to know how yarn deals with `>=` dependences. After all, I want to believe that I won't need to have the file regenerated each time a dependency has a new release...

**Review by marado — COMMENTED** [review]
> I here opted not to do so, maybe an habit flaw (in particular,
> following the traditions from package and dependency management on
> projects like Debian). I'll be open to accept arguments against this.

Seems that I'm not alone in thinking this way. While I'm not 100% aligned with https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e , it explains why semver is "not for me", I'm more into "romantic versioning" than "semantic versioning".

**Comment by tralves** [comment]
IMHO, npm dependencies should not be handled the same way for Debian simply because they are not shared. If a dependency _is_ shared, such as _node_, then we should treat it like you said.

That's why I think in this case we want 1) the most stable version, and 2) to be able to lock the dependency to a version we know it works to avoid "_oh, but it works on my machine_" errors. In fact, that `yarn.lock` comes fulfil this npm shortcoming. It locks the dependencies versions in a file that is versioned and thus shared by the entire team.

When I run `yarn upgrade`, yarn will re-process the `package-json`, upgrade/downgrade dependencies accordingly, and then update `yarn.lock`.

So this is why I think we should keep version 1.1.0 for dirty.

_Nostagic moment_
A long, long time ago, in college, someone said to me: "Having the new bugs is much better than having the old bugs". I have been generally following this mantra since then. That guy was YOU, @marado! Embrace the new bugs! Move to 1.1.0!

**Comment by marado** [comment]
Seems that somehow the mail<->github integration is not working as expected... Let's try this comment again:

Now I see where your objection comes from...

> IMHO, npm dependencies should not be handled the same way for Debian simply because they are not shared. If a dependency is shared, such as node, then we should treat it like you said.

Well, I see two issues here.

One is that you are assuming npm dependencies are local (not shared). That's not always the case, and one should not assume it is. Any package you have installed globally can satisfy, as a dependency, any other package you might have depending on it. Of course, it will only satisfy if the installed version is allowed as a dependency.

The other is that you seem to try to solve an issue that is already solved, by design. _If_ a dependency is going to be installed by npm, it will automatically choose the "most recent version" from those allowed. In other words: on your scenario of "there's no global dirty.is", npm will install 1.1.0 no matter if there's >=0.9.9 or >=1.1.0 in the deps file.

> That's why I think in this case we want 1) the most stable version, and 2) to be able to lock the dependency to a version we know it works to avoid "oh, but it works on my machine" errors. In fact, that yarn.lock comes fulfil this npm shortcoming.

We are always "able to lock to a version" (the deps list is mutable) but are you proposing that, right from the start we have them locked into known goods? I.e., are you saying we should depend on "1.1.0" and not on ">=1.1.0"?

> When I run yarn upgrade, yarn will re-process the package-json, upgrade/downgrade dependencies accordingly, and then update yarn.lock.

OK, so we don't need to worry about regenerating the lock file, good.

> Nostagic moment
> 
> A long, long time ago, in college, someone said to me: "Having the new bugs is much better than having the old bugs". I have been generally following this mantra since then. That guy was YOU, @marado! Embrace the new bugs! Move to 1.1.0!

I still say that, and it still gets misinterpreted ;-) Think of that as part of my positive approach on dependencies: we should depend on >= 1.1.0 instead of being locked on 1.1.0. Yes, it might surface new and interesting bugs, but it might also get you rid of a few old and bad smelling ones.

I'm not against using the latest and greatest releases, I'm against forcing them on users when there's no technical reason to (specially when you might be avoiding a dependency hell issue in the process).

**Comment by marado** [comment]
Now I see where your objection comes from...

On Oct 21, 2016 02:35, "Tiago Alves" notifications@github.com wrote:

> IMHO, npm dependencies should not be handled the same way for Debian
> simply because they are not shared. If a dependency is shared, such as
> node, then we should treat it like you said.

Well, I see two issues here.

One is that you are assuming npm dependencies are local (not shared).
That's not always the case, and one should not assume it is. Any package
you have installed globally can satisfy, as a dependency, any other package
you might have depending on it. Of course, it will only satisfy if the
installed version is allowed as a dependency.

The other is that you seem to try to solve an issue that is already solved,
by design. _If_ a dependency is going to be installed by npm, it will
automatically choose the "most recent version" from those allowed. In other
words: on your scenario of "there's no global dirty.is", npm will install
1.1.0 no matter if there's >=0.9.9 or >=1.1.0 in the deps file.

> That's why I think in this case we want 1) the most stable version, and
> 2) to be able to lock the dependency to a version we know it works to avoid
> "oh, but it works on my machine" errors. In fact, that yarn.lock comes
> fulfil this npm shortcoming.

We are always "able to lock to a version" (the deps list is mutable) but
are you proposing that, right from the start we have them locked into known
goods? I.e., are you saying we should depend on "1.1.0" and not on
">=1.1.0"?

> It locks the dependencies versions in a file that is versioned and thus
> shared by the entire team.
> 
> When I run yarn upgrade, yarn will re-process the package-json,
> upgrade/downgrade dependencies accordingly, and then update yarn.lock.

OK, so we don't need to worry about regenerating the lock file, good.

> So this is why I think we should keep version 1.1.0 for dirty.
> 
> Nostagic moment
> A long, long time ago, in college, someone said to me: "Having the new
> bugs is much better than having the old bugs". I have been generally
> following this mantra since then. That guy was YOU, @marado! Embrace the
> new bugs! Move to 1.1.0!

I still say that, and it still gets misinterpreted ;-) Think of that as
part of my positive approach on dependencies: we should depend on >= 1.1.0
instead of being locked on 1.1.0. Yes, it might surface new and interesting
bugs, but it might also get you rid of a few old and bad smelling ones.

I'm not against using the latest and greatest releases, I'm against forcing
them on users when there's no technical reason to (specially when you might
be avoiding a dependency hell issue in the process).

**Comment by marado** [comment]
Since https://github.com/marado/TalkerNode/pull/42 is merged, I'm closing this.

**Pull request closed without merging**
